Changed in POM based on http://jenkins-ci.361315.n4.nabble.com/Internal-Error-when-using-AWT-even-with-headless-true-td3768281.html
Jenkins Error:

ERROR: Failed to parse POMs
java.io.IOException: Remote call on Channel to Maven [java, -cp, /Users/Shared/Jenkins/Home/plugins/maven-plugin/WEB-INF/lib/maven3-agent-1.2.jar:/Users/Shared/Jenkins/Home/tools/hudson.tasks.Maven_MavenInstallation/maven/boot/plexus-classworlds-2.4.jar, org.jvnet.hudson.maven3.agent.Maven3Main, /Users/Shared/Jenkins/Home/tools/hudson.tasks.Maven_MavenInstallation/maven, /Users/Shared/Jenkins/Home/war/WEB-INF/lib/remoting-2.23.jar, /Users/Shared/Jenkins/Home/plugins/maven-plugin/WEB-INF/lib/maven3-interceptor-1.2.jar, 63629] failed
	at hudson.remoting.Channel.call(Channel.java:681)
	at hudson.maven.ProcessCache$MavenProcess.call(ProcessCache.java:156)
	at hudson.maven.MavenModuleSetBuild$MavenModuleSetBuildExecution.doRun(MavenModuleSetBuild.java:766)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:586)
	at hudson.model.Run.execute(Run.java:1576)
	at hudson.maven.MavenModuleSetBuild.run(MavenModuleSetBuild.java:486)
	at hudson.model.ResourceController.execute(ResourceController.java:88)
	at hudson.model.Executor.run(Executor.java:241)
Caused by: java.lang.InternalError: Can't connect to window server - not enough permissions.
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1827)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1724)
	at java.lang.Runtime.loadLibrary0(Runtime.java:823)
	at java.lang.System.loadLibrary(System.java:1045)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:50)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.awt.Toolkit.loadLibraries(Toolkit.java:1605)
	at java.awt.Toolkit.<clinit>(Toolkit.java:1627)
	at java.awt.Color.<clinit>(Color.java:263)